source "http://rubygems.org"

gem 'appetite', :git => 'git://github.com/slivu/appetite.git'
gem 'e', :git => 'git://github.com/espresso/espresso.git'

# alternative for activesupport/dependencies [http://apidock.com/rails/ActiveSupport/Dependencies]
gem 'class_loader'


group :development do
  # rerun restarts your server, only if files changed, better than shotgun for Rack-apps
  gem 'rerun'
  gem 'rb-inotify' if RUBY_PLATFORM.downcase.include?("linux")
  gem 'rb-fsevent', '~> 0.9.1' if RUBY_PLATFORM.downcase.include?("darwin")

  # just use thin, much better, than webbrick
  gem 'thin'
end